version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - .docker/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: sh -c "composer install && npm install && php-fpm"
    depends_on:
      - webserver
      - db

  webserver:
    image: nginx:1.17-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/data/db/:/var/lib/mysql/
